apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: project
data:
  default.conf: |
    server {
        listen 5000;
        location / {
            proxy_pass http://backend:5001;
        }
    }
