apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: project
  labels:
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
