apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: project
data:
  default.conf: |
    server {
        listen 80;
        location /backend {
            proxy_pass http://frontend:5000;
        }
    }
