apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: project
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-app
        image: badamiec3/frontend:latest
        ports:
        - containerPort: 5000
