           sh 'pwd'
           sh 'aws configure set aws_access_key_id ${AWS_ACCESS_KEY}'
           sh 'aws configure set aws_secret_access_key ${AWS_SECRET_KEY}'
           sh 'sudo su ubuntu'
           sh 'whoami'
           sh 'aws configure set aws_access_key_id ${AWS_ACCESS_KEY}'
           sh 'aws configure set aws_secret_access_key ${AWS_SECRET_KEY}'
           sh 'sudo su jenkins' 
           sh 'whoami'
